#!/usr/bin/env bash
# script that displays The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)


for cmd in $(ls)
do
	base_name="${cmd%%.*}"
	echo "$base_name"
done
