#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.90.32.25
    HostName 54.90.32.25
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
